export const TARGET_API_LABELS = {
  api_particulier: 'API Particulier',
  franceconnect: 'FranceConnect',
  api_entreprise: 'API Entreprise',
  preuve_covoiturage: 'Registre de preuve de covoiturage',
  api_impot_particulier_sandbox: 'API Impôt particulier (Bac à sable)',
  api_impot_particulier_production: 'API Impôt particulier (Production)',
  api_impot_particulier_fc_sandbox: 'API Impôt particulier (FC - Bac à sable)',
  api_impot_particulier_fc_production:
    'API Impôt particulier (FC - Production)',
  api_r2p_sandbox: 'API R2P (Bac à sable)',
  api_r2p_production: 'API R2P (Production)',
  api_ficoba_sandbox: 'API FICOBA (Bac à sable)',
  api_ficoba_production: 'API FICOBA (Production)',
  api_droits_cnam: 'API Droits CNAM',
  le_taxi_clients: 'le.Taxi - applicatifs clients',
  le_taxi_chauffeurs: 'le.Taxi - applicatifs chauffeurs',
  cartobio: 'CartoBio - Territoires',
  aidants_connect: 'Aidants Connect',
  francerelance_fc: 'FranceRelance - Guichet FranceConnect',
  francerelance_api_restreinte: 'FranceRelance - subvention API restreinte',
  francerelance_api_ouverte: 'FranceRelance - subvention API ouverte',
};

export const TARGET_API_WITH_ENROLLMENTS_IN_PRODUCTION_ENV = [
  'franceconnect',
  'api_entreprise',
  'api_particulier',
  'api_impot_particulier_fc_sandbox',
  'api_impot_particulier_fc_production',
  'api_droits_cnam',
  'francerelance_fc',
];

export const API_ICONS = {
  api_particulier: 'logo-beta-gouv.svg',
  franceconnect: 'logo-fc-with-label.png',
  api_entreprise: 'logo-beta-gouv.svg',
  api_impot_particulier_sandbox: 'logo-dgfip-with-label.png',
  api_impot_particulier_production: 'logo-dgfip-with-label.png',
  api_impot_particulier_fc_sandbox: 'logo-dgfip-with-label.png',
  api_impot_particulier_fc_production: 'logo-dgfip-with-label.png',
  api_r2p_sandbox: 'logo-dgfip-with-label.png',
  api_r2p_production: 'logo-dgfip-with-label.png',
  api_ficoba_sandbox: 'logo-dgfip-with-label.png',
  api_ficoba_production: 'logo-dgfip-with-label.png',
  api_droits_cnam: 'logo-cnam.jpg',
  le_taxi_clients: 'logo-le.taxi.svg',
  le_taxi_chauffeurs: 'logo-le.taxi.svg',
  cartobio: 'logo-cartobio-text.svg',
  aidants_connect: 'aidants-connect_logo.png',
  francerelance_fc: 'logo-fc-with-label.png',
  francerelance_api_restreinte: 'logo-francerelance.png',
  francerelance_api_ouverte: 'logo-francerelance.png',
};
